# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import app.services.amanita_pb2 as amanita__pb2


class DatalabAmanitaAPIServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListContent = channel.unary_unary(
        '/datalabamanitaapi.DatalabAmanitaAPIService/ListContent',
        request_serializer=amanita__pb2.ListContentRequest.SerializeToString,
        response_deserializer=amanita__pb2.ResultSet.FromString,
        )
    self.Item = channel.unary_unary(
        '/datalabamanitaapi.DatalabAmanitaAPIService/Item',
        request_serializer=amanita__pb2.ItemRequest.SerializeToString,
        response_deserializer=amanita__pb2.MinimalItem.FromString,
        )
    self.ListSimilarItems = channel.unary_unary(
        '/datalabamanitaapi.DatalabAmanitaAPIService/ListSimilarItems',
        request_serializer=amanita__pb2.ListSimilarItemsRequest.SerializeToString,
        response_deserializer=amanita__pb2.ResultSet.FromString,
        )
    self.HealthCheck = channel.unary_unary(
        '/datalabamanitaapi.DatalabAmanitaAPIService/HealthCheck',
        request_serializer=amanita__pb2.HealthCheckRequest.SerializeToString,
        response_deserializer=amanita__pb2.HealthCheckResponse.FromString,
        )


class DatalabAmanitaAPIServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListContent(self, request, context):
    """List content

    Get a list of media items that match a set of filters.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Item(self, request, context):
    """Get details for a single media item by URI.

    Get details for a single media item by passing in the item URI.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListSimilarItems(self, request, context):
    """Get media items related to the given URI.

    Given an item URI, return list of similar media items.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HealthCheck(self, request, context):
    """Health check

    The healthcheck endpoint is a NOOP to check services response
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DatalabAmanitaAPIServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListContent': grpc.unary_unary_rpc_method_handler(
          servicer.ListContent,
          request_deserializer=amanita__pb2.ListContentRequest.FromString,
          response_serializer=amanita__pb2.ResultSet.SerializeToString,
      ),
      'Item': grpc.unary_unary_rpc_method_handler(
          servicer.Item,
          request_deserializer=amanita__pb2.ItemRequest.FromString,
          response_serializer=amanita__pb2.MinimalItem.SerializeToString,
      ),
      'ListSimilarItems': grpc.unary_unary_rpc_method_handler(
          servicer.ListSimilarItems,
          request_deserializer=amanita__pb2.ListSimilarItemsRequest.FromString,
          response_serializer=amanita__pb2.ResultSet.SerializeToString,
      ),
      'HealthCheck': grpc.unary_unary_rpc_method_handler(
          servicer.HealthCheck,
          request_deserializer=amanita__pb2.HealthCheckRequest.FromString,
          response_serializer=amanita__pb2.HealthCheckResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'datalabamanitaapi.DatalabAmanitaAPIService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
