language: python
python:
- 3.6
script: pytest
env:
- PYTHONPATH=.:$PYTHONPATH
before_deploy: "echo Deploying to Pypi.."
after_deploy: "echo Deployed to Pypi."
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
