sudo: required

language: python

services:
  - docker

python:
- 3.6
script: pytest
env:
- PYTHONPATH=.:$PYTHONPATH

before_install:
  - docker build -t notbinary/connected-data-amanita .

before_deploy: "echo Deploying to Docker Hub..."
after_deploy: "echo Deployed to Docker Hub."
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
